default_language_version:
  python: python

exclude: ^(temp/|omegaconf/vendor/)

# Hook versions should match those in requirements/dev.txt
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.22
    hooks:
      - id: ruff-check
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
