language: python
python: 2.7
install: pip install tox
script: tox
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.0
      env: TOXENV=py30
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
