"""Regression tests for the vendored ANTLR4 runtime.

Each test guards against a specific failure mode that would only show up
once a particular Python release ships. The vendored runtime is
regenerated by ``build_helpers/get_vendored.py``; if you re-vendor and
this file fails, update the post-vendor patches in that script too.
"""

from __future__ import annotations

import re
import warnings
from pathlib import Path

import pytest

VENDOR_ROOT = Path(__file__).resolve().parent.parent / "omegaconf" / "vendor"


@pytest.fixture(scope="module")
def vendor_python_files() -> list[Path]:
    return [p for p in VENDOR_ROOT.rglob("*.py") if p.is_file()]


def test_no_typing_io_imports(vendor_python_files: list[Path]) -> None:
    """``typing.io`` was deprecated in 3.8 and removed in 3.13.

    Importing it on 3.13+ is a hard ``ImportError``; on 3.10-3.12 it
    emits a ``DeprecationWarning``. ``TextIO`` has always been available
    from the top-level ``typing`` module, so any reference here means
    the post-vendor patch in ``build_helpers/get_vendored.py`` was
    skipped. See issue #936.
    """
    pattern = re.compile(r"\btyping\.io\b")
    offenders = [p for p in vendor_python_files if pattern.search(p.read_text("utf8"))]
    assert not offenders, "vendored files still reference typing.io: " + ", ".join(
        str(p.relative_to(VENDOR_ROOT)) for p in offenders
    )


def test_vendor_imports_clean() -> None:
    """Importing the vendored modules must not emit DeprecationWarning.

    On Python 3.13+ the legacy ``typing.io`` branch is a hard
    ImportError; on 3.10-3.12 it surfaces as a DeprecationWarning. Both
    failure modes are caught here.
    """
    with warnings.catch_warnings():
        warnings.simplefilter("error", DeprecationWarning)
        from omegaconf.vendor.antlr4 import Lexer, Parser  # noqa: F401
        from omegaconf.vendor.antlr4.xpath import XPathLexer  # noqa: F401
